### PR TITLE
Documenting trezord more thoroughly

### PR DESCRIPTION
**Pull request by karelbilek**
I have made some changes to the documentation.

Always open to more ideas :)

### CODE REVIEW

**Comment by runn1ng** [comment]
you can of course check the rendered version here

https://github.com/trezor/trezord/blob/docs/README.md

**Comment by runn1ng** [comment]
Can I merge that? (Will probably squash the commits) I think inperfect docs are better than no docs :)

**Comment by prusnak** [comment]
Yes, pls. Squash & merge.

**Comment by runn1ng** [comment]
Merging

**Pull request merged**
