### PR TITLE
Add basic FreeBSD support and tarball creation script

### PR DESCRIPTION
**Pull request by alexdupre**

### CODE REVIEW

**Review by NicolaiSoeborg — APPROVED** [review]

**Comment by dariusc93** [comment]
You might want to add to the README stating for freebsd users to use `-I/usr/local/include` over `-I/usr/include` if they are also going to be regenerating the protobuf files.

**Comment by alexdupre** [comment]
Actually I have FreeBSD port ready to be committed, including the switch from hidapi to libusb.

**Comment by alexdupre** [comment]
Port (with libusb implementation) committed.

- [SVN Commit](https://svnweb.freebsd.org/ports?view=revision&revision=458661)
- [Port](https://svnweb.freebsd.org/ports/head/security/trezord/)
- [FreshPort](https://www.freshports.org/security/trezord/)

**Comment by prusnak** [comment]
Thanks for the contribution!

We are phasing out this implementation of the bridge and replacing it with a new version here: https://github.com/trezor/trezord-go

Would you like to try packaging this implementation as well?

If you find issues, please report them to that repository. Thank you!

**Comment by alexdupre** [comment]
I was able to build and package it, I'll create a pull request with the required changes.
I though it was a 100% compatible replacement of `trezord` but as far as I've seen it listens to a different port (w/o ssl support) and it doesn't seem supported by `wallet.trezor.io` yet. Can you shed some light?

**Comment by prusnak** [comment]
Yes. New browsers (Firefox, Chrom{e,ium}) do not require HTTPS for localhost connections even when accessed from secure context. This allowed us to drop SSL dependency (which was a PITA).

Newly deployed version of wallet will connect to the correct HTTP port.

You can try beta-wallet.trezor.io which already does this.

**Comment by alexdupre** [comment]
That's great, re: SSL, the fetch of Let's Encrypt certificate was nice but tricky.

I did try also beta-wallet.trezor.io, without success. I now see the following error in console:

Blocked loading mixed active content “http://127.0.0.1:21325/”

So it seems that my seamonkey is not considered a "new browser" :-(

I've tried with firefox and it start communicating with the daemon, but it panics on hid write, I open an issue in the other repo.

**Comment by prusnak** [comment]
I think the change from Firefox will propagate to Seamonkey soon.

**Comment by saleemrashid** [comment]
> Seamonkey

That still exists? 🤣 

More seriously, since SeaMonkey is based on ESR, this will be an issue for Tor Browser as well.

**Comment by alexdupre** [comment]
For the records, support of mixed content on localhost was added in Firefox 55, while Firefox ESR is based on version 52.  Next ESR major version won't be released before May 2018 and will be based on Firefox 60.

**Pull request merged**
